{{- if .Values.oceanbase.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opencoze.fullname" . }}-oceanbase
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opencoze.labels" . | nindent 4 }}
    app.kubernetes.io/component: oceanbase
{{- end }}
